# scripts/01_install_requirements.R
# Install all requirements for scripts
# install.packages(c("dplyr", "devtools", "sf", "wk", "worrms", "here", "httr2", "tidyr", "ggplot2", "readr", "rfishbase", "rnaturalearth", "robis", "rgbif", "stringr", "ggtext"))
# devtools::install_github("ropensci/mregions2", build_vignettes = TRUE)
# devtools::install_github("bio-oracle/biooracler")
library(biooracler)
library(dplyr)
# library(mregions2)
library(sf)
library(wk)
library(worrms)
library(here)
library(httr2)
library(tidyr)
library(ggplot2)
library(readr)
library(rfishbase)
library(rnaturalearth)
library(robis)
library(rgbif)
library(stringr)
library(ggtext)
library(ggvegan)
library(vegan)