# scripts/06_run_standard_sdms.R
#-------------------------------------------------------------------------------
# Run Standard Species Distribution Models (SDMs)
#
# Workflow:
# 1. Load species lists and paths to PCA rasters (generated by script 05).
# 2. Loop through each species group (anemone, anemonefish).
# 3. Loop through each species within the group.
# 4. Loop through each environmental scenario (current, future).
# 5. Load the appropriate PCA raster stack for the group/scenario.
# 6. Load/clean/thin individual species occurrences.
# 7. Check if minimum number of occurrences is met.
# 8. Generate background points.
# 9. Run ENMeval using the sdm_modeling_helpers::run_sdm_enmeval.
# 10. Select the best model and generate prediction raster using sdm_modeling_helpers::predict_sdm_best.
# 11. Save prediction raster, ENMeval results object, and best model summary.
#-------------------------------------------------------------------------------
cat("--- Running Script 06: Run Standard SDMs ---\n")

# Ensure config is loaded
if (!exists("config")) {
  source("scripts/config.R")
  if (!exists("config")) {
    stop("Failed to load config object from scripts/config.R")
  }
}

# Load necessary packages
pacman::p_load(terra, sf, dplyr, readr, ENMeval, tools)

# Source helper functions
sdm_helper_path <- file.path(config$helpers_dir, "sdm_modeling_helpers.R")
if (!file.exists(sdm_helper_path)) stop("SDM Helper file not found: ", sdm_helper_path)
source(sdm_helper_path)

# --- Load Inputs ---

# 1. Species Lists
tryCatch({
  anemone_species <- readr::read_csv(config$anemone_species_list_file, show_col_types = FALSE)
  anemonefish_species <- readr::read_csv(config$anemonefish_species_list_file, show_col_types = FALSE)
}, error = function(e) {
  stop("Failed to load species list CSV files. Run script 02 first. Error: ", e$message)
})

# Combine into a list for looping
species_list_combined <- list(
  anemone = anemone_species,
  anemonefish = anemonefish_species
)
group_occ_dirs <- list(
  anemone = config$anemone_occurrence_dir,
  anemonefish = config$anemonefish_occurrence_dir
)

# 2. PCA Raster Paths (from script 05)
if (!file.exists(config$pca_raster_paths_rds_path)) {
  stop("PCA raster paths file not found: ", config$pca_raster_paths_rds_path, ". Run script 05 first.")
}
pca_raster_paths <- readRDS(config$pca_raster_paths_rds_path)

# 3. Create output subdirectories if they don't exist
dir.create(config$predictions_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(config$results_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(config$models_dir, recursive = TRUE, showWarnings = FALSE)

# --- Main Loop: Group -> Species -> Scenario ---

total_sdms_run <- 0
total_sdms_skipped <- 0

for (group_name in names(species_list_combined)) {
  cat("\n=========================================================\n")
  cat("Processing Group:", group_name, "\n")
  cat("=========================================================\n")
  
  species_df <- species_list_combined[[group_name]]
  occurrence_folder <- group_occ_dirs[[group_name]]
  
  for (i in 1:nrow(species_df)) {
    
    species_name_sanitized <- gsub(" ", "_", species_df$scientificName[i]) # For filenames
    species_aphia_id <- species_df$AphiaID[i]
    
    cat("\n-----------------------------------------------------\n")
    cat("Processing Species:", species_df$scientificName[i], "(", i, "/", nrow(species_df), "of", group_name, ")\n")
    cat("-----------------------------------------------------\n")
    
    # Load and clean individual occurrences ONCE per species
    occ_sf_clean <- load_clean_individual_occ(species_aphia_id, occurrence_folder, config)
    
    if(is.null(occ_sf_clean) || nrow(occ_sf_clean) < config$min_occurrences_sdm) {
      warning("Skipping species ", species_df$scientificName[i], ": Not enough occurrences after cleaning (", nrow(occ_sf_clean), "<", config$min_occurrences_sdm, ").", call.=FALSE)
      total_sdms_skipped <- total_sdms_skipped + length(config$env_scenarios) # Skip all scenarios for this species
      next # Skip to next species
    }
    cat("  Loaded and cleaned", nrow(occ_sf_clean), "initial occurrences.\n")
    
    for (scenario in config$env_scenarios) {
      cat("  --- Scenario:", scenario, "---\n")
      
      # --- Define Output Paths for this species/scenario ---
      pred_file <- file.path(config$predictions_dir, paste0("sdm_prediction_", species_name_sanitized, "_", scenario, ".tif"))
      results_file <- file.path(config$results_dir, paste0("sdm_results_", species_name_sanitized, "_", scenario, ".rds"))
      eval_file <- file.path(config$results_dir, paste0("sdm_eval_", species_name_sanitized, "_", scenario, ".csv"))
      model_obj_file <- file.path(config$models_dir, paste0("sdm_model_", species_name_sanitized, "_", scenario, ".rds")) # Save best model object
      
      # --- Check if prediction exists and skip if not forcing ---
      if (!config$force_rerun$run_standard_sdms && file.exists(pred_file)) {
        cat("    Prediction file already exists. Skipping SDM run.\n")
        total_sdms_skipped <- total_sdms_skipped + 1
        next # Skip to next scenario
      }
      
      # 1. Load PCA predictor stack for this group/scenario
      pca_stack_path <- pca_raster_paths[[group_name]][[scenario]]
      if (is.null(pca_stack_path) || !file.exists(pca_stack_path)) {
        warning("PCA raster stack not found for ", group_name, "/", scenario, " at path: ", pca_stack_path, ". Skipping SDM run.", call. = FALSE)
        total_sdms_skipped <- total_sdms_skipped + 1
        next # Skip to next scenario
      }
      predictor_stack <- tryCatch({
        terra::rast(pca_stack_path)
      }, error = function(e){
        warning("Failed to load PCA raster stack: ", pca_stack_path, "\nError: ", e$message, call.=FALSE)
        NULL
      })
      if(is.null(predictor_stack)) { total_sdms_skipped <- total_sdms_skipped + 1; next }
      cat("    Loaded predictor stack:", basename(pca_stack_path), "\n")
      
      # 2. Thin individual occurrences using the loaded predictor stack
      occ_sf_thinned <- thin_individual_occ(occ_sf_clean, predictor_stack, config)
      
      if(is.null(occ_sf_thinned) || nrow(occ_sf_thinned) < config$min_occurrences_sdm) {
        warning("Skipping scenario ", scenario, ": Not enough occurrences after thinning (", nrow(occ_sf_thinned), "<", config$min_occurrences_sdm, ").", call.=FALSE)
        total_sdms_skipped <- total_sdms_skipped + 1
        next # Skip to next scenario
      }
      cat("    Thinned occurrences:", nrow(occ_sf_thinned), "points.\n")
      
      # 3. Generate Background Points
      background_points <- generate_sdm_background(predictor_stack, config$background_points_n, config)
      if (is.null(background_points)) {
        warning("Failed to generate background points for scenario ", scenario, ". Skipping SDM run.", call. = FALSE)
        total_sdms_skipped <- total_sdms_skipped + 1
        next # Skip to next scenario
      }
      
      # 4. Run SDM (ENMeval)
      enmeval_results <- run_sdm_enmeval(occ_sf_thinned, predictor_stack, background_points, config)
      if (is.null(enmeval_results)) {
        warning("ENMeval failed for scenario ", scenario, ". Skipping SDM run.", call. = FALSE)
        total_sdms_skipped <- total_sdms_skipped + 1
        next # Skip to next scenario
      }
      # Save ENMeval object (contains all models and full results)
      tryCatch({
        saveRDS(enmeval_results, file = results_file)
        cat("    ENMeval results object saved to:", basename(results_file), "\n")
      }, error=function(e){warning("Failed to save ENMeval results object: ", e$message)})
      
      # Save just the evaluation table as CSV for quick review
      tryCatch({
        readr::write_csv(enmeval_results@results, file = eval_file)
        cat("    Evaluation table saved to:", basename(eval_file), "\n")
      }, error=function(e){warning("Failed to save evaluation table: ", e$message)})
      
      
      # 5. Select Best Model and Predict
      prediction_raster <- predict_sdm_best(enmeval_results, predictor_stack, config)
      
      if (is.null(prediction_raster)) {
        warning("Prediction failed for scenario ", scenario, ". Skipping saving.", call. = FALSE)
        total_sdms_skipped <- total_sdms_skipped + 1
        next # Skip to next scenario
      }
      
      # 6. Save Prediction Raster
      tryCatch({
        terra::writeRaster(prediction_raster, filename = pred_file, overwrite = TRUE, gdal=c("COMPRESS=LZW", "TFW=YES"))
        cat("    Prediction raster saved to:", basename(pred_file), "\n")
        total_sdms_run <- total_sdms_run + 1
      }, error=function(e){
        warning("Failed to save prediction raster: ", e$message, call.=FALSE)
        total_sdms_skipped <- total_sdms_skipped + 1
      })
      
      # 7. Save Best Model Object (optional but recommended for reproducibility)
      tryCatch({
        # Re-find best model index (code duplicated from predict helper, maybe refactor)
        eval_results_df <- enmeval_results@results
        metric <- config$sdm_evaluation_metric
        if(!metric %in% names(eval_results_df)) metric <- "AICc" # Fallback
        select_best <- if (metric == "AICc") which.min else which.max
        valid_rows <- !is.na(eval_results_df[[metric]])
        if(sum(valid_rows) > 0) {
          best_model_index <- select_best(eval_results_df[[metric]][valid_rows])
          original_indices <- which(valid_rows)
          best_model_row_index <- original_indices[best_model_index]
          best_model_obj <- enmeval_results@models[[best_model_row_index]]
          saveRDS(best_model_obj, file = model_obj_file)
          cat("    Best model object saved to:", basename(model_obj_file), "\n")
        }
      }, error=function(e){warning("Failed to save best model object: ", e$message)})
      
      
      # Clean up memory for this scenario
      rm(predictor_stack, occ_sf_thinned, background_points, enmeval_results, prediction_raster); gc()
      
    } # End scenario loop
    
    # Clean up species data
    rm(occ_sf_clean); gc()
    
  } # End species loop
} # End group loop

cat("\n=========================================================\n")
cat("Standard SDM runs finished.\n")
cat("Total SDMs successfully run and saved:", total_sdms_run, "\n")
cat("Total SDMs skipped (due to errors, missing data, or existing files):", total_sdms_skipped, "\n")
cat("=========================================================\n")

cat("\n--- Script 06 finished. ---\n")
#-------------------------------------------------------------------------------